version: '3.3'

services: 
    app:
        container_name: astro
        volumes:
            - "~/Public/astro:/app:rw"
            - /app/node_modules
        restart: always
        build: .
        ports: 
            - "${HOST_APP_PORT}:${CONTAINER_APP_PORT}"
        environment:
            - "HOST_APP_PORT=${HOST_APP_PORT}"
            - "CONTAINER_APP_PORT=${CONTAINER_APP_PORT}"
            - "CONTACT_FORM_EMAIL=${CONTACT_FORM_EMAIL}"
            - "CONTACT_FORM_PASS=${CONTACT_FORM_PASS}"
