version: '3'

services: 
    app:
        container_name: astro
        restart: always
        build: .
        ports: 
            - '80:5001'
        environment:
            - APP_PORT=5001
        volumes:
            - "~/Public/astro:/app:rw"
